package fi.capeismi.fish.uistelupaivakirja.web.dao;
// Generated Jul 22, 2011 3:04:04 PM by Hibernate Tools 3.2.1.GA

import java.util.LinkedHashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Collection generated by hbm2java
 */
@SuppressWarnings("serial")
@XmlRootElement(name = "TrollingObjects")
@Entity
public class Collection implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	@ManyToOne
	@JoinColumn(name = "USER_ID")
	private User user;

	@ManyToOne
	private Type type;

	@Column
	private int revision;

	@OneToMany(mappedBy = "collection", cascade = CascadeType.ALL)
	@OrderBy("object_identifier")
	private Set<Trollingobject> trollingobjects = new LinkedHashSet<Trollingobject>(0);

	@XmlTransient
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@XmlTransient
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@XmlTransient
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	@XmlAttribute
	public int getRevision() {
		return this.revision;
	}

	public void setRevision(int revision) {
		this.revision = revision;
	}

	@XmlElement(name = "TrollingObject")
	public Set<Trollingobject> getTrollingobjects() {
		return this.trollingobjects;
	}

	public void setTrollingobjects(Set<Trollingobject> trollingobjects) {
		this.trollingobjects = trollingobjects;
	}

	@XmlAttribute
	public int getMaxId() {
		int maxid = 0;
		for (Trollingobject o : this.trollingobjects) {
			if (o.getObjectIdentifier() > maxid) {
				maxid = o.getObjectIdentifier();
			}

		}

		return maxid;
	}

}
