package fi.capeismi.fish.uistelupaivakirja.web.dao;
// Generated Jul 22, 2011 3:04:04 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Event generated by hbm2java
 */
@SuppressWarnings("serial")
@XmlRootElement
@Entity
public class Event implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	@ManyToOne
	@JoinColumn(name = "trolling_id")
	private Trollingobject trollingobject;

	@Column
	private String fish_air_temp;
	@Column
	private String fish_coord_lat;
	@Column
	private String fish_coord_lon;
	@Column
	private String fish_cr;
	@Column
	private String fish_getter;
	@Column
	private String fish_group;
	@Column
	private String fish_group_amount;
	@Column
	private String fish_length;
	@Column
	private String fish_line_weight;
	@Column
	private String fish_method;
	@Column
	private String fish_misc_text;
	@Column
	private String fish_pressure;
	@Column
	private String fish_pressure_change;
	@Column
	private String fish_rain;
	@Column
	private String fish_release_width;
	@Column
	private String fish_species;
	@Column
	private String fish_spot_depth;
	@Column
	private String fish_time;
	@Column
	private String fish_total_depth;
	@Column
	private String fish_trolling_speed;
	@Column
	private String fish_undersize;
	@Column
	private String fish_water_temp;
	@Column
	private String fish_weather;
	@Column
	private String fish_weight;
	@Column
	private String fish_wind;
	@Column
	private String fish_wind_direction;
	@Column
	private String lure;
	@Column
	private String type;

	@XmlTransient
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@XmlTransient
	public Trollingobject getTrollingobject() {
		return this.trollingobject;
	}

	public void setTrollingobject(Trollingobject trollingobject) {
		this.trollingobject = trollingobject;
	}

	// Getters
	public String getFish_air_temp() {
		return fish_air_temp;
	}

	public String getFish_coord_lat() {
		return fish_coord_lat;
	}

	public String getFish_coord_lon() {
		return fish_coord_lon;
	}

	public String getFish_cr() {
		return fish_cr;
	}

	public String getFish_getter() {
		return fish_getter;
	}

	public String getFish_group() {
		return fish_group;
	}

	public String getFish_group_amount() {
		return fish_group_amount;
	}

	public String getFish_length() {
		return fish_length;
	}

	public String getFish_line_weight() {
		return fish_line_weight;
	}

	public String getFish_method() {
		return fish_method;
	}

	public String getFish_misc_text() {
		return fish_misc_text;
	}

	public String getFish_pressure() {
		return fish_pressure;
	}

	public String getFish_pressure_change() {
		return fish_pressure_change;
	}

	public String getFish_rain() {
		return fish_rain;
	}

	public String getFish_release_width() {
		return fish_release_width;
	}

	public String getFish_species() {
		return fish_species;
	}

	public String getFish_spot_depth() {
		return fish_spot_depth;
	}

	public String getFish_time() {
		return fish_time;
	}

	public String getFish_total_depth() {
		return fish_total_depth;
	}

	public String getFish_trolling_speed() {
		return fish_trolling_speed;
	}

	public String getFish_undersize() {
		return fish_undersize;
	}

	public String getFish_water_temp() {
		return fish_water_temp;
	}

	public String getFish_weather() {
		return fish_weather;
	}

	public String getFish_weight() {
		return fish_weight;
	}

	public String getFish_wind() {
		return fish_wind;
	}

	public String getFish_wind_direction() {
		return fish_wind_direction;
	}

	public String getLure() {
		return lure;
	}

	public String getType() {
		return type;
	}

	// Setters
	public void setFish_air_temp(String fish_air_temp) {
		this.fish_air_temp = fish_air_temp;
	}

	public void setFish_coord_lat(String fish_coord_lat) {
		this.fish_coord_lat = fish_coord_lat;
	}

	public void setFish_coord_lon(String fish_coord_lon) {
		this.fish_coord_lon = fish_coord_lon;
	}

	public void setFish_cr(String fish_cr) {
		this.fish_cr = fish_cr;
	}

	public void setFish_getter(String fish_getter) {
		this.fish_getter = fish_getter;
	}

	public void setFish_group(String fish_group) {
		this.fish_group = fish_group;
	}

	public void setFish_group_amount(String fish_group_amount) {
		this.fish_group_amount = fish_group_amount;
	}

	public void setFish_length(String fish_length) {
		this.fish_length = fish_length;
	}

	public void setFish_line_weight(String fish_line_weight) {
		this.fish_line_weight = fish_line_weight;
	}

	public void setFish_method(String fish_method) {
		this.fish_method = fish_method;
	}

	public void setFish_misc_text(String fish_misc_text) {
		this.fish_misc_text = fish_misc_text;
	}

	public void setFish_pressure(String fish_pressure) {
		this.fish_pressure = fish_pressure;
	}

	public void setFish_pressure_change(String fish_pressure_change) {
		this.fish_pressure_change = fish_pressure_change;
	}

	public void setFish_rain(String fish_rain) {
		this.fish_rain = fish_rain;
	}

	public void setFish_release_width(String fish_release_width) {
		this.fish_release_width = fish_release_width;
	}

	public void setFish_species(String fish_species) {
		this.fish_species = fish_species;
	}

	public void setFish_spot_depth(String fish_spot_depth) {
		this.fish_spot_depth = fish_spot_depth;
	}

	public void setFish_time(String fish_time) {
		this.fish_time = fish_time;
	}

	public void setFish_total_depth(String fish_total_depth) {
		this.fish_total_depth = fish_total_depth;
	}

	public void setFish_trolling_speed(String fish_trolling_speed) {
		this.fish_trolling_speed = fish_trolling_speed;
	}

	public void setFish_undersize(String fish_undersize) {
		this.fish_undersize = fish_undersize;
	}

	public void setFish_water_temp(String fish_water_temp) {
		this.fish_water_temp = fish_water_temp;
	}

	public void setFish_weather(String fish_weather) {
		this.fish_weather = fish_weather;
	}

	public void setFish_weight(String fish_weight) {
		this.fish_weight = fish_weight;
	}

	public void setFish_wind(String fish_wind) {
		this.fish_wind = fish_wind;
	}

	public void setFish_wind_direction(String fish_wind_direction) {
		this.fish_wind_direction = fish_wind_direction;
	}

	public void setLure(String lure) {
		this.lure = lure;
	}

	public void setType(String type) {
		this.type = type;
	}

}
