package fi.capeismi.fish.uistelupaivakirja.web.dao;
// Generated Aug 19, 2011 9:44:24 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Trollingobject generated by hbm2java
 */
@SuppressWarnings("serial")
@XmlRootElement
@Entity
public class Trollingobject implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	@ManyToOne
	private Collection collection;

	private int object_identifier;
	private String city;
	private String color;
	private String color_back;
	private String color_belly;
	private String color_class;
	private String color_contrast;
	private String color_side;
	private String date;
	private String description;
	private String favorite;
	private String lure_type;
	private String maker;
	private String model;
	private String name;
	private String nickname;
	private String invisible;
	private String notvisible;
	private String place;
	private String routefile;
	private String size;
	private String time_end;
	private String time_start;
	private String waypointfile;

	@XmlAttribute
	public String getType() {
		if (collection != null) {
			return this.collection.getType().getName();
		}

		return "";
	}

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "trollingobject")
	@OrderBy("id")
	private Set<Event> events = new LinkedHashSet<Event>(0);

	@XmlTransient
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@XmlTransient
	public Collection getCollection() {
		return this.collection;
	}

	public void setCollection(Collection collection) {
		this.collection = collection;
	}

	@XmlAttribute(name = "id")
	public int getObjectIdentifier() {
		return this.object_identifier;
	}

	public void setObjectIdentifier(int objectIdentifier) {
		this.object_identifier = objectIdentifier;
	}

	@XmlElementWrapper(name = "PropertyList")
	@XmlElement(name = "PropertyListItem")
	public Set<Event> getEvents() {
		if (this.events == null) {
			return new HashSet<Event>();
		}
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

	// GETTERS
	public String getCity() {
		return city;
	}

	public String getColor() {
		return color;
	}

	public String getColor_back() {
		return color_back;
	}

	public String getColor_belly() {
		return color_belly;
	}

	public String getColor_class() {
		return color_class;
	}

	public String getColor_contrast() {
		return color_contrast;
	}

	public String getColor_side() {
		return color_side;
	}

	public String getDate() {
		return date;
	}

	public String getDescription() {
		return description;
	}

	public String getFavorite() {
		return favorite;
	}

	public String getLure_type() {
		return lure_type;
	}

	public String getMaker() {
		return maker;
	}

	public String getModel() {
		return model;
	}

	public String getName() {
		return name;
	}

	public String getNickname() {
		return nickname;
	}

	public String getInvisible() {
		return invisible;
	}

	public String getPlace() {
		return place;
	}

	public String getRoutefile() {
		return routefile;
	}

	public String getSize() {
		return size;
	}

	public String getTime_end() {
		return time_end;
	}

	public String getTime_start() {
		return time_start;
	}

	public String getWaypointfile() {
		return waypointfile;
	}

	// Setters

	public void setCity(String city) {
		this.city = city;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public void setColor_back(String color_back) {
		this.color_back = color_back;
	}

	public void setColor_belly(String color_belly) {
		this.color_belly = color_belly;
	}

	public void setColor_class(String color_class) {
		this.color_class = color_class;
	}

	public void setColor_contrast(String color_contrast) {
		this.color_contrast = color_contrast;
	}

	public void setColor_side(String color_side) {
		this.color_side = color_side;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setFavorite(String favorite) {
		this.favorite = favorite;
	}

	public void setLure_type(String lure_type) {
		this.lure_type = lure_type;
	}

	public void setMaker(String maker) {
		this.maker = maker;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public void setInvisible(String notvisible) {
		this.invisible = notvisible;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public void setRoutefile(String routefile) {
		this.routefile = routefile;
	}

	public void setSize(String size) {
		this.size = size;
	}

	public void setTime_end(String time_end) {
		this.time_end = time_end;
	}

	public void setTime_start(String time_start) {
		this.time_start = time_start;
	}

	public void setWaypointfile(String waypointfile) {
		this.waypointfile = waypointfile;
	}

	public String getNotvisible() {
		return notvisible;
	}

	public void setNotvisible(String notvisible) {
		this.notvisible = notvisible;
	}

}
