package fi.capeismi.fish.uistelupaivakirja.web.dao;
// Generated Jul 22, 2011 3:04:04 PM by Hibernate Tools 3.2.1.GA


import java.util.LinkedHashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Collection generated by hbm2java
 */
@XmlRootElement(name="TrollingObjects")
public class Collection  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Type type;
     private int revision;
     private Set<Trollingobject> trollingobjects = new LinkedHashSet<Trollingobject>(0);

    public Collection() {
    }

	
    public Collection(User user, Type type, int revision) {
        this.user = user;
        this.type = type;
        this.revision = revision;
    }
    public Collection(User user, Type type, int revision, Set<Trollingobject> trollingobjects) {
       this.user = user;
       this.type = type;
       this.revision = revision;
       this.trollingobjects = trollingobjects;
    }
   
    @XmlTransient
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @XmlTransient
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    
    @XmlTransient
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }
    
    @XmlAttribute
    public int getRevision() {
        return this.revision;
    }
    
    public void setRevision(int revision) {
        this.revision = revision;
    }
    
    @XmlElement(name="TrollingObject")
    public Set<Trollingobject> getTrollingobjects() {
        return this.trollingobjects;
    }
    
    public void setTrollingobjects(Set<Trollingobject> trollingobjects) {
        this.trollingobjects = trollingobjects;
    }

    @XmlAttribute
    public int getMaxId() {
        int maxid = 0;
        for(Trollingobject o: this.trollingobjects) {
            if(o.getObjectIdentifier() > maxid) {
                maxid = o.getObjectIdentifier();
            }
                
        }
        
        return maxid;
    }


}


