package fi.capeismi.fish.uistelupaivakirja.web.dao;
// Generated Jul 22, 2011 3:04:04 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Collection generated by hbm2java
 */
public class Collection  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Type type;
     private int revision;
     private Set<Trollingobject> trollingobjects = new HashSet<Trollingobject>(0);

    public Collection() {
    }

	
    public Collection(User user, Type type, int revision) {
        this.user = user;
        this.type = type;
        this.revision = revision;
    }
    public Collection(User user, Type type, int revision, Set<Trollingobject> trollingobjects) {
       this.user = user;
       this.type = type;
       this.revision = revision;
       this.trollingobjects = trollingobjects;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }
    public int getRevision() {
        return this.revision;
    }
    
    public void setRevision(int revision) {
        this.revision = revision;
    }
    public Set<Trollingobject> getTrollingobjects() {
        return this.trollingobjects;
    }
    
    public void setTrollingobjects(Set<Trollingobject> trollingobjects) {
        this.trollingobjects = trollingobjects;
    }




}


