package fi.capeismi.fish.uistelupaivakirja.web.dao;
// Generated Jul 22, 2011 3:04:04 PM by Hibernate Tools 3.2.1.GA



/**
 * Eventproperty generated by hbm2java
 */
public class Eventproperty  implements java.io.Serializable {


     private Integer id;
     private Event event;
     private Keyvalue keyvalue;

    public Eventproperty() {
    }

    public Eventproperty(Event event, Keyvalue keyvalue) {
       this.event = event;
       this.keyvalue = keyvalue;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public Keyvalue getKeyvalue() {
        return this.keyvalue;
    }
    
    public void setKeyvalue(Keyvalue keyvalue) {
        this.keyvalue = keyvalue;
    }




}


