package fi.capeismi.fish.uistelupaivakirja.web.dao;
// Generated Jul 22, 2011 3:04:04 PM by Hibernate Tools 3.2.1.GA


import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private Integer id;
     private Trollingobject trollingobject;
     private Set<Eventproperty> eventproperties = new LinkedHashSet<Eventproperty>(0);

    public Event() {
    }

	
    public Event(Trollingobject trollingobject) {
        this.trollingobject = trollingobject;
    }
    public Event(Trollingobject trollingobject, Set<Eventproperty> eventproperties) {
       this.trollingobject = trollingobject;
       this.eventproperties = eventproperties;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Trollingobject getTrollingobject() {
        return this.trollingobject;
    }
    
    public void setTrollingobject(Trollingobject trollingobject) {
        this.trollingobject = trollingobject;
    }
    public Set<Eventproperty> getEventproperties() {
        return this.eventproperties;
    }
    
    public void setEventproperties(Set<Eventproperty> eventproperties) {
        this.eventproperties = eventproperties;
    }




}


