package fi.capeismi.fish.uistelupaivakirja.web.dao;
// Generated Jun 19, 2011 4:55:37 PM by Hibernate Tools 3.2.1.GA



/**
 * Keyvalue generated by hbm2java
 */
public class Keyvalue  implements java.io.Serializable {


     private Integer id;
     private Trollingobject trollingobject;
     private String keyname;
     private String value;

    public Keyvalue() {
    }

	
    public Keyvalue(Trollingobject trollingobject, String keyname) {
        this.trollingobject = trollingobject;
        this.keyname = keyname;
    }
    public Keyvalue(Trollingobject trollingobject, String keyname, String value) {
       this.trollingobject = trollingobject;
       this.keyname = keyname;
       this.value = value;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Trollingobject getTrollingobject() {
        return this.trollingobject;
    }
    
    public void setTrollingobject(Trollingobject trollingobject) {
        this.trollingobject = trollingobject;
    }
    public String getKeyname() {
        return this.keyname;
    }
    
    public void setKeyname(String keyname) {
        this.keyname = keyname;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


