package fi.capeismi.fish.uistelupaivakirja.web.dao;
// Generated Jul 22, 2011 3:04:04 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Keyvalue generated by hbm2java
 */
public class Keyvalue  implements java.io.Serializable {


     private Integer id;
     private String keyname;
     private String value;
     private Set<Property> properties = new HashSet<Property>(0);
     private Set<Eventproperty> eventproperties = new HashSet<Eventproperty>(0);

    public Keyvalue() {
    }

	
    public Keyvalue(String keyname) {
        this.keyname = keyname;
    }
    public Keyvalue(String keyname, String value, Set<Property> properties, Set<Eventproperty> eventproperties) {
       this.keyname = keyname;
       this.value = value;
       this.properties = properties;
       this.eventproperties = eventproperties;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getKeyname() {
        return this.keyname;
    }
    
    public void setKeyname(String keyname) {
        this.keyname = keyname;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Set<Property> getProperties() {
        return this.properties;
    }
    
    public void setProperties(Set<Property> properties) {
        this.properties = properties;
    }
    public Set<Eventproperty> getEventproperties() {
        return this.eventproperties;
    }
    
    public void setEventproperties(Set<Eventproperty> eventproperties) {
        this.eventproperties = eventproperties;
    }




}


