package fi.capeismi.fish.uistelupaivakirja.web.dao;
// Generated Jun 19, 2011 4:55:37 PM by Hibernate Tools 3.2.1.GA



/**
 * Propertylistitem generated by hbm2java
 */
public class Propertylistitem  implements java.io.Serializable {


     private Integer id;
     private Propertylist propertylist;
     private String keyname;
     private String value;

    public Propertylistitem() {
    }

	
    public Propertylistitem(Propertylist propertylist, String keyname) {
        this.propertylist = propertylist;
        this.keyname = keyname;
    }
    public Propertylistitem(Propertylist propertylist, String keyname, String value) {
       this.propertylist = propertylist;
       this.keyname = keyname;
       this.value = value;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Propertylist getPropertylist() {
        return this.propertylist;
    }
    
    public void setPropertylist(Propertylist propertylist) {
        this.propertylist = propertylist;
    }
    public String getKeyname() {
        return this.keyname;
    }
    
    public void setKeyname(String keyname) {
        this.keyname = keyname;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


