package fi.capeismi.fish.uistelupaivakirja.web.dao;
// Generated Jun 19, 2011 4:55:37 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Propertylist generated by hbm2java
 */
public class Propertylist  implements java.io.Serializable {


     private Integer id;
     private Trollingobject trollingobject;
     private Set propertylistitems = new HashSet(0);

    public Propertylist() {
    }

	
    public Propertylist(Trollingobject trollingobject) {
        this.trollingobject = trollingobject;
    }
    public Propertylist(Trollingobject trollingobject, Set propertylistitems) {
       this.trollingobject = trollingobject;
       this.propertylistitems = propertylistitems;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Trollingobject getTrollingobject() {
        return this.trollingobject;
    }
    
    public void setTrollingobject(Trollingobject trollingobject) {
        this.trollingobject = trollingobject;
    }
    public Set getPropertylistitems() {
        return this.propertylistitems;
    }
    
    public void setPropertylistitems(Set propertylistitems) {
        this.propertylistitems = propertylistitems;
    }




}


