package fi.capeismi.fish.uistelupaivakirja.web.dao;
// Generated Jul 22, 2011 3:04:04 PM by Hibernate Tools 3.2.1.GA



/**
 * Property generated by hbm2java
 */
public class Property  implements java.io.Serializable {


     private Integer id;
     private Trollingobject trollingobject;
     private Keyvalue keyvalue;

    public Property() {
    }

    public Property(Trollingobject trollingobject, Keyvalue keyvalue) {
       this.trollingobject = trollingobject;
       this.keyvalue = keyvalue;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Trollingobject getTrollingobject() {
        return this.trollingobject;
    }
    
    public void setTrollingobject(Trollingobject trollingobject) {
        this.trollingobject = trollingobject;
    }
    public Keyvalue getKeyvalue() {
        return this.keyvalue;
    }
    
    public void setKeyvalue(Keyvalue keyvalue) {
        this.keyvalue = keyvalue;
    }




}


