package fi.capeismi.fish.uistelupaivakirja.web.dao;
// Generated Jun 19, 2011 4:55:37 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Revision generated by hbm2java
 */
public class Revision  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Date creationDate;
     private Set trollingobjects = new HashSet(0);

    public Revision() {
    }

	
    public Revision(User user) {
        this.user = user;
    }
    public Revision(User user, Date creationDate, Set trollingobjects) {
       this.user = user;
       this.creationDate = creationDate;
       this.trollingobjects = trollingobjects;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Set getTrollingobjects() {
        return this.trollingobjects;
    }
    
    public void setTrollingobjects(Set trollingobjects) {
        this.trollingobjects = trollingobjects;
    }




}


