package fi.capeismi.fish.uistelupaivakirja.web.dao;
// Generated Aug 19, 2011 9:44:24 PM by Hibernate Tools 3.2.1.GA


import fi.capeismi.fish.uistelupaivakirja.web.model.RestfulException;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Trollingobject generated by hbm2java
 */
@XmlRootElement
public class Trollingobject  implements java.io.Serializable {


    private Integer id;
    private Collection collection;
    private int objectIdentifier;
    private String city;           
    private String color;          
    private String color_back;     
    private String color_belly;   
    private String color_class;    
    private String color_contrast; 
    private String color_side;     
    private String date;           
    private String description;    
    private String favorite;       
    private String lure_type;      
    private String maker;          
    private String model;          
    private String name;           
    private String nickname;       
    private String notvisible;     
    private String place;          
    private String routefile;      
    private String size;           
    private String time_end;       
    private String time_start;    
    private String waypointfile;

    @XmlAttribute
    public String getType() {
        if(collection != null) {
            return this.collection.getType().getName();
        }
        
        return "";
    }


    private Set<Event> events = new LinkedHashSet<Event>(0);

    public Trollingobject() {
    }

	
    public Trollingobject(Collection collection, int objectIdentifier) {
        this.collection = collection;
        this.objectIdentifier = objectIdentifier;
    }
    public Trollingobject(Collection collection, int objectIdentifier, Set<Event> events) {
       this.collection = collection;
       this.objectIdentifier = objectIdentifier;
       this.events = events;
    }
    
    public Map<String, String> getProperties() {
        Map<String, String> retval = new HashMap<String, String>();
        retval.put("city", city);           
        retval.put("color", color);          
        retval.put("color_back", color_back);     
        retval.put("color_belly", color_belly);   
        retval.put("color_class", color_class);     
        retval.put("color_contrast", color_contrast); 
        retval.put("color_side", color_side);     
        retval.put("date", date);           
        retval.put("description", description);     
        retval.put("favorite", favorite);        
        retval.put("lure_type", lure_type);       
        retval.put("maker", maker);          
        retval.put("model", model);           
        retval.put("name", name);            
        retval.put("nickname", nickname);        
        retval.put("notvisible", notvisible);      
        retval.put("place", place);           
        retval.put("routefile", routefile);       
        retval.put("size", size);            
        retval.put("time_end", time_end);       
        retval.put("time_start", time_start);     
        retval.put("waypointfile", waypointfile); 
        return retval;
    }
    
    public void setProperty(String property, String value) {
        for(Method method: this.getClass().getMethods())
        {
            if(method.getName().equalsIgnoreCase("set"+property)) {
                try {
                    Object[] args = new Object[1];
                    args[0] = value;
                    
                    method.invoke(this, args);
                    return;
                } catch (Exception e) {
                    throw new RestfulException(e);
                }
            }
        }
        throw new RestfulException("Unknown property: "+property);
    }
   
    @XmlTransient
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @XmlTransient
    public Collection getCollection() {
        return this.collection;
    }
    
    public void setCollection(Collection collection) {
        this.collection = collection;
    }
    
    @XmlAttribute(name="id")
    public int getObjectIdentifier() {
        return this.objectIdentifier;
    }
    
    public void setObjectIdentifier(int objectIdentifier) {
        this.objectIdentifier = objectIdentifier;
    }

    @XmlElementWrapper(name="PropertyList")
    @XmlElement(name="PropertyListItem")
    public Set<Event> getEvents() {
        return this.events;
    }
    
    public void setEvents(Set<Event> events) {
        this.events = events;
    }


    // GETTERS
    public String getCity() {
        return city;
    }

    public String getColor() {
        return color;
    }

    public String getColor_back() {
        return color_back;
    }

    public String getColor_belly() {
        return color_belly;
    }

    public String getColor_class() {
        return color_class;
    }

    public String getColor_contrast() {
        return color_contrast;
    }

    public String getColor_side() {
        return color_side;
    }

    public String getDate() {
        return date;
    }

    public String getDescription() {
        return description;
    }

    public String getFavorite() {
        return favorite;
    }

    public String getLure_type() {
        return lure_type;
    }

    public String getMaker() {
        return maker;
    }

    public String getModel() {
        return model;
    }

    public String getName() {
        return name;
    }

    public String getNickname() {
        return nickname;
    }

    public String getNotvisible() {
        return notvisible;
    }

    public String getPlace() {
        return place;
    }

    public String getRoutefile() {
        return routefile;
    }

    public String getSize() {
        return size;
    }

    public String getTime_end() {
        return time_end;
    }

    public String getTime_start() {
        return time_start;
    }

    public String getWaypointfile() {
        return waypointfile;
    }
    
    // Setters
    
    public void setCity(String city) {
        this.city = city;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public void setColor_back(String color_back) {
        this.color_back = color_back;
    }

    public void setColor_belly(String color_belly) {
        this.color_belly = color_belly;
    }

    public void setColor_class(String color_class) {
        this.color_class = color_class;
    }

    public void setColor_contrast(String color_contrast) {
        this.color_contrast = color_contrast;
    }

    public void setColor_side(String color_side) {
        this.color_side = color_side;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setFavorite(String favorite) {
        this.favorite = favorite;
    }

    public void setLure_type(String lure_type) {
        this.lure_type = lure_type;
    }

    public void setMaker(String maker) {
        this.maker = maker;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public void setNotvisible(String notvisible) {
        this.notvisible = notvisible;
    }

    public void setPlace(String place) {
        this.place = place;
    }

    public void setRoutefile(String routefile) {
        this.routefile = routefile;
    }

    public void setSize(String size) {
        this.size = size;
    }

    public void setTime_end(String time_end) {
        this.time_end = time_end;
    }

    public void setTime_start(String time_start) {
        this.time_start = time_start;
    }

    public void setWaypointfile(String waypointfile) {
        this.waypointfile = waypointfile;
    }

}


