package fi.capeismi.fish.uistelupaivakirja.web.dao;
// Generated Aug 19, 2011 9:44:24 PM by Hibernate Tools 3.2.1.GA


import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Trollingobject generated by hbm2java
 */
public class Trollingobject  implements java.io.Serializable {


     private Integer id;
     private Collection collection;
     private int objectIdentifier;
     private Set<Trollingproperty> trollingproperties = new LinkedHashSet<Trollingproperty>(0);
     private Set<Event> events = new LinkedHashSet<Event>(0);

    public Trollingobject() {
    }

	
    public Trollingobject(Collection collection, int objectIdentifier) {
        this.collection = collection;
        this.objectIdentifier = objectIdentifier;
    }
    public Trollingobject(Collection collection, int objectIdentifier, Set<Trollingproperty> trollingproperties, Set<Event> events) {
       this.collection = collection;
       this.objectIdentifier = objectIdentifier;
       this.trollingproperties = trollingproperties;
       this.events = events;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Collection getCollection() {
        return this.collection;
    }
    
    public void setCollection(Collection collection) {
        this.collection = collection;
    }
    public int getObjectIdentifier() {
        return this.objectIdentifier;
    }
    
    public void setObjectIdentifier(int objectIdentifier) {
        this.objectIdentifier = objectIdentifier;
    }
    public Set<Trollingproperty> getTrollingproperties() {
        return this.trollingproperties;
    }
    
    public void setTrollingproperties(Set<Trollingproperty> trollingproperties) {
        this.trollingproperties = trollingproperties;
    }
    public Set<Event> getEvents() {
        return this.events;
    }
    
    public void setEvents(Set<Event> events) {
        this.events = events;
    }




}


