package fi.capeismi.fish.uistelupaivakirja.web.dao;
// Generated Aug 19, 2011 9:44:24 PM by Hibernate Tools 3.2.1.GA



/**
 * Trollingproperty generated by hbm2java
 */
public class Trollingproperty  implements java.io.Serializable {


     private Integer id;
     private Trollingobject trollingobject;
     private String keyname;
     private String value;

    public Trollingproperty() {
    }

	
    public Trollingproperty(Trollingobject trollingobject, String keyname) {
        this.trollingobject = trollingobject;
        this.keyname = keyname;
    }
    public Trollingproperty(Trollingobject trollingobject, String keyname, String value) {
       this.trollingobject = trollingobject;
       this.keyname = keyname;
       this.value = value;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Trollingobject getTrollingobject() {
        return this.trollingobject;
    }
    
    public void setTrollingobject(Trollingobject trollingobject) {
        this.trollingobject = trollingobject;
    }
    public String getKeyname() {
        return this.keyname;
    }
    
    public void setKeyname(String keyname) {
        this.keyname = keyname;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


