package fi.capeismi.fish.uistelupaivakirja.web.dao;
// Generated Jun 19, 2011 4:55:37 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private Set revisions = new HashSet(0);

    public User() {
    }

    public User(String username, String password, Set revisions) {
       this.username = username;
       this.password = password;
       this.revisions = revisions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getRevisions() {
        return this.revisions;
    }
    
    public void setRevisions(Set revisions) {
        this.revisions = revisions;
    }




}


