package fi.capeismi.fish.uistelupaivakirja.web.dao;
// Generated Aug 25, 2011 6:12:00 PM by Hibernate Tools 3.2.1.GA


import fi.capeismi.fish.uistelupaivakirja.web.model.AnnotatedView;
import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * User generated by hbm2java
 */
@XmlRootElement(name="userinfo")
public class User  implements java.io.Serializable, AnnotatedView {


     private Integer id;
     private String username;
     private String password;
     private String plaintextpassword;
     private String salt;

     private Boolean publishlocation;
     private Boolean publishplace;
     private Boolean publishlure;
     private Boolean publishfish;
     private Boolean publishtrip;
     private Set<Collection> collections = new HashSet<Collection>(0);

    public User() {
    }

    public User(String username, String password, Boolean publishlocation, Boolean publishplace, Boolean publishlure, Boolean publishfish, Boolean publishtrip, Set<Collection> collections) {
       this.username = username;
       this.password = password;
       this.publishlocation = publishlocation;
       this.publishplace = publishplace;
       this.publishlure = publishlure;
       this.publishfish = publishfish;
       this.publishtrip = publishtrip;
       this.collections = collections;
    }
   
    @XmlElement
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @XmlElement
    public String getPlaintextpassword() {
        return plaintextpassword;
    }

    public void setPlaintextpassword(String plaintextpassword) {
        this.plaintextpassword = plaintextpassword;
    }
    
    @XmlTransient
    public String getSalt() {
        return salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }
    
    @XmlElement
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @XmlTransient
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @XmlElement
    public Boolean getPublishlocation() {
        return this.publishlocation;
    }
    
    public void setPublishlocation(Boolean publishlocation) {
        this.publishlocation = publishlocation;
    }
    
    @XmlElement
    public Boolean getPublishplace() {
        return this.publishplace;
    }
    
    public void setPublishplace(Boolean publishplace) {
        this.publishplace = publishplace;
    }
    
    @XmlElement
    public Boolean getPublishlure() {
        return this.publishlure;
    }
    
    public void setPublishlure(Boolean publishlure) {
        this.publishlure = publishlure;
    }
    
    @XmlElement
    public Boolean getPublishfish() {
        return this.publishfish;
    }
    
    public void setPublishfish(Boolean publishfish) {
        this.publishfish = publishfish;
    }
    
    @XmlElement
    public Boolean getPublishtrip() {
        return this.publishtrip;
    }
    
    public void setPublishtrip(Boolean publishtrip) {
        this.publishtrip = publishtrip;
    }
    
    @XmlTransient
    public Set<Collection> getCollections() {
        return this.collections;
    }
    
    public void setCollections(Set<Collection> collections) {
        this.collections = collections;
    }




}


